[package]
authors = ["Till Höppner <till@hoeppner.ws>"]
name = "cpuline"
version = "0.1.0"

[dependencies]
clap = "=2.20.5"
env_logger = "=0.3.5"
libc = "0.2.20"
log = "=0.3.7"
vec_map = "=0.6.0"

[profile.dev]
opt-level = 2
